# MySQL Configuration
mysql:
  enable: false
  host: localhost
  port: 3306
  database: database
  username: username
  password: password

#VaultEconommy
default:
  name: main
  start: 30